name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCS_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          export PROJECT_ID=$(jq -r '.project_id' credentials.json)
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: cd terraform && terraform init

      - name: Apply Terraform Configuration
        env:
          TF_VAR_gcs_credentials: ${{ secrets.GCS_CREDENTIALS }}
          TF_VAR_project_id: ${{ env.PROJECT_ID }}
        run: cd terraform && terraform apply -auto-approve

      # TEST
      - name: Capture Terraform Output
        run: |
          echo "Fetching Terraform outputs..."
          cd terraform
          terraform output
          BUCKET_NAME=$(terraform output -raw petfinder_bucket)
          echo "GCS_BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Clean Up Credentials
        if: always()
        run: rm -f credentials.json

