name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCS_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          export PROJECT_ID=$(jq -r '.project_id' credentials.json)
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: cd terraform && terraform init

      - name: Apply Terraform Configuration
        env:
          TF_VAR_gcs_credentials: ${{ secrets.GCS_CREDENTIALS }}
          TF_VAR_project_id: ${{ env.PROJECT_ID }}
        run: cd terraform && terraform apply -auto-approve

      # TEST - going to create .env instead and then read in with daily yml
      - name: Capture Terraform Output and Save to .env
        run: |
          echo "Fetching Terraform outputs..."
          cd terraform
          echo "GCS_BUCKET_NAME=$(terraform output -raw petfinder_bucket)" > $GITHUB_WORKSPACE/.env

      # echo "PROJECT_ID=$(terraform output -raw project_id)" >> $GITHUB_WORKSPACE/.env

      - name: Verify .env File
        run: cat .env

      # END
      - name: Clean Up Credentials
        if: always()
        run: rm -f credentials.json

